version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    networks:
      - sogo_default
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - type: volume
        source: sogo_data
        target: /usr/lib/GNUstep/SOGo/
      - ./nginx/sogo.conf:/etc/nginx/conf.d/sogo.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

  app:
    build:
      context: .
      dockerfile: ./sogo/Dockerfile
    deploy:
      replicas: $REPLICAS_APP
    command: bash -c "
              /usr/sbin/sogod
              -WONoDetach YES
              -WOPidFile /var/lib/sogo/sogo.pid
              -WOLogFile /proc/1/fd/1
              -WOWorkersCount $WCOUNT
              -WOPort $WOPORT
      "
    networks:
      - sogo_default
    restart: unless-stopped
    volumes:
    - type: volume
      source: sogo_data
      target: /usr/lib/GNUstep/SOGo/
    environment:
      - WCOUNT=${WCOUNT}
      - WOPORT=${WOPORT}
      - REPLICAS_APP=${REPLICAS_APP}
    depends_on:
      - memcache
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

  memcache:
    restart: unless-stopped
    image: memcached:latest
    networks:
      - sogo_default

networks:
  sogo_default:

volumes:
  sogo_data:
    name: sogo_app_data
